In [ ]:
# Tokenizar

In [ ]:
import re

In [ ]:
def tokenize(texto):
    tokens = []
    keywords = re.compile(r'\b(if|then|else|while)\b')
    identificador = re.compile(r'[a-zA-Z][a-zA-Z0-9]*')
    numeros = re.compile(r'\d+')
    operadores = re.compile(r'[\+\-\*\/]')
    delimitador = re.compile(r'[()]|;')
    # Recorrer palabra por palabra y asignar tipo
    for palabra in texto.split():
        if keywords.match(palabra):
            tokens.append(('Keyword', palabra))
        elif identificador.match(palabra):
            tokens.append(('Identificador', palabra))
        elif numeros.match(palabra):
            tokens.append(('Número', palabra))
        elif operadores.match(palabra):
            tokens.append(('Operador', palabra))
        elif delimitador.match(palabra):
            tokens.append(('Delimitador', palabra))
        else:
            print(f'Token desconocido: {palabra}')
    return tokens

In [10]:
# Ejemplo de uso
texto = 'if x > 5 then ( y = y + 1 ) ; else z = z - 1 ; @'
tokens = tokenize(texto)
print(tokens)

Token desconocido: >
Token desconocido: =
Token desconocido: =
Token desconocido: @
[('Keyword', 'if'), ('Identificador', 'x'), ('Número', '5'), ('Keyword', 'then'), ('Delimitador', '('), ('Identificador', 'y'), ('Identificador', 'y'), ('Operador', '+'), ('Número', '1'), ('Delimitador', ')'), ('Delimitador', ';'), ('Keyword', 'else'), ('Identificador', 'z'), ('Identificador', 'z'), ('Operador', '-'), ('Número', '1'), ('Delimitador', ';')]

In [11]:
import pandas as pd

In [12]:
tabla = pd.DataFrame(tokens, columns=['Tipo', 'Valor'])
tabla

             Tipo Valor
0         Keyword    if
1   Identificador     x
2          Número     5
3         Keyword  then
4     Delimitador     (
5   Identificador     y
6   Identificador     y
7        Operador     +
8          Número     1
9     Delimitador     )
10    Delimitador     ;
11        Keyword  else
12  Identificador     z
13  Identificador     z
14       Operador     -
15         Número     1
16    Delimitador     ;

In [13]:
tabla['Valor'].unique()

array(['if', 'x', '5', 'then', '(', 'y', '+', '1', ')', ';', 'else', 'z',
       '-'], dtype=object)

In [14]:
resumen = pd.DataFrame(tabla['Tipo'].value_counts())
resumen['Encontrados'] = [tabla[tabla['Tipo'] == tipo]['Valor'].unique() for tipo in resumen.index]
resumen

               count       Encontrados
Tipo
Identificador      5         [x, y, z]
Delimitador        4         [(, ), ;]
Keyword            3  [if, then, else]
Número             3            [5, 1]
Operador           2            [+, -]

In [17]:
tabla[tabla['Tipo']=='Identificador']['Valor'].unique()

array(['x', 'y', 'z'], dtype=object)

In [ ]:
# Implementar el analizador de los tokens
def parse(tokens):
    # Funcion auxiliar para consumir cada token
    def consume(tipo_esperado):
        global token_actual
        if token_actual[0] == tipo_esperado:
            global indice_token
            token_actual = tokens[indice_token]
            indice_token += 1
        else:
            raise Exception(f'Se esperaba {tipo_esperado}, pero se encontro un {token_actual}')
        
    # Reglas de produccion como funciones
    def E():
        # Implementar la regla de produccion de expresiones
        T()
        while token_actual[0] in ['+', '-']:
            operador = token_actual[1]
            consume('Operador')
            T()
    def T():
        # Implementacion de la regla de produccion de terminos
        F()
        while token_actual[0] in ['*', '/']:
            operador = token_actual[1]
            consume('Operador')
            F()
    def F():
        # Implementacion de la regla de produccion de factores

    # Inicializacion de variables
    global token_actual, indice_token
    token_actual = token[0]
    indice_token[1]

    # Iniciar el analisis
    E()

    # Si se consumieron todos los tokens, el analisis fue exitosos
    if indice_token == len(tokens):
        return True
    else:
        raise Exception('Error de sintaxis')